name = "free_iff_flat_iff_proj"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["FreeIffFlatIffProj"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "FreeIffFlatIffProj"
